version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - "./.localstack:/var/lib/localstack"
  app:
    build: .
    container_name: nest-auth-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app                  
      - ./sqlite:/app/sqlite     
    environment:
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=supersecret
      - JWT_EXPIRES_IN=1h
      - DATABASE_FILE=./sqlite/database.sqlite
    command: npm run start:dev   